# -*- coding: utf-8 -*-
"""Copy of Pandas 01_Task .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JWniC_pfYnJkhFd8ge3kZPjMIDieIndl

# <center><font color='RED'>**CAT Reloaded Data Science**</center></font>
<center>Beginner's task 5_Pandas 01</center>

<h1 align='center'><font color='brown'> Pandas Task

##  <a href='https://www.kaggle.com/toramky/automobile-dataset'> **Dataset**

### import pandas
"""

import pandas as pd

"""### import data

>**note**: if all columns don't appear, make them appear
"""

pd.set_option('display.max_columns', None)
df = pd.read_csv('Automobile_data.csv')

"""[link text](https://)### Show first 5 rows in data"""

df.head()

"""### Show last 5 rows in data"""

df.tail()

"""### Show information about data"""

df.info()

"""### filter the data which has (body_style) sedan **and** (engine_type) is ohc"""

filt=((df['body-style']=='sedan') & (df['engine_type']=='ohc'))
df[filt]

"""### Show data which (make) is bmw"""

filt=(df['make']=='bmw')
df[filt]

"""### Show the shape of data"""

df.shape

"""### Delete (price) column and show data without it"""

df.drop(columns='price')

"""### Show more details about (body style)"""

df["body-style"].describe()

"""### Show count of missing values in each column"""

df.isnull().sum()

"""### Check if the data contain duplicated values or not **and** if it has ,remove these values"""

df.duplicated()
df.drop_duplicates()



pd.to_numeric(df['normalized-losses'],errors="coerce")

"""### Replace the missing values in each columns"""

df.fillna(5)

"""### Save all changes in new excel file called <font color='blue'>cleaned data

1.   List item

1.   List item
2.   List item


2.   List item


"""

cleanded_data = 'cleaned_data.xlsx'
df.to_excel(cleaned_data, index=False)

"""# **2. CodeForces Problems** 💡

<a href='https://codeforces.com/contest/1883/problem/A'> <font color='blue'>**Problem 1** (Morning)</a> </font>
"""

https://codeforces.com/contest/1883/submission/252735480

"""<a href='https://codeforces.com/contest/1878/problem/B'> <font color='blue'>**Problem 2** (Aleksa and Stack)</a> </font>"""

https://codeforces.com/contest/1878/submission/252739640

"""#       """